package com.ninja.dietician.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "DietProject_Table")
public class Morbidity {
	
	@DynamoDBHashKey(attributeName = "PK")
	@DynamoDBAutoGeneratedKey
	private String morbidityId;
	
	@DynamoDBAttribute
	private String testId;
	
	@DynamoDBAttribute
	private String infoType;
	
	@DynamoDBAttribute
	private String morbidityName;
	
	@DynamoDBAttribute
	private String morbidityTestId;
	
	@DynamoDBAttribute
	private String morbidityTestName;
	
	@DynamoDBAttribute
	private String morbidityTestUnit;
	
	@DynamoDBAttribute
	private String morbidityTestMarkerRef;
	
	@DynamoDBAttribute
	private String createdOn;
	
	@DynamoDBAttribute
	private String modifiedOn;

}
